In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("ecommerce_orders.csv")

In [4]:
df.head(10)

,Order ID,Product Category,Vendor,Order Date,Shipping Date,Delivery Date,Region,Delivery Status,Return Status,Return Reason
0,ORD0000,Clothing,VendorC,2024-07-20,2024-07-21,2024-07-30,East,Delayed,Not Returned,NaN
1,ORD0001,Beauty,VendorB,2024-11-11,2024-11-12,2024-11-17,West,Delivered,Returned,Late
2,ORD0002,Clothing,VendorB,2024-12-06,2024-12-08,2024-12-14,North,Delayed,Not Returned,NaN
3,ORD0003,Home,VendorA,2024-12-25,2024-12-26,2024-12-30,East,Delivered,Not Returned,NaN
4,ORD0004,Clothing,VendorA,2024-05-19,2024-05-22,2024-05-28,West,Delayed,Not Returned,NaN
5,ORD0005,Home,VendorC,2024-02-26,2024-02-27,2024-03-04,West,Delayed,Not Returned,NaN
6,ORD0006,Electronics,VendorB,2024-07-12,2024-07-13,2024-07-22,West,Delayed,Returned,Wrong item
7,ORD0007,Home,VendorB,2024-04-02,2024-04-04,2024-04-11,North,Delayed,Not Returned,NaN
8,ORD0008,Home,VendorA,2024-02-26,2024-02-28,2024-03-04,South,Delivered,Not Returned,NaN
9,ORD0009,Clothing,VendorA,2024-08-21,2024-08-22,2024-08-25,West,Delivered,Not Returned,NaN

In [5]:
df.columns

Index(['Order ID', 'Product Category', 'Vendor', 'Order Date', 'Shipping Date',
       'Delivery Date', 'Region', 'Delivery Status', 'Return Status',
       'Return Reason'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          1000 non-null   object
 1   Product Category  1000 non-null   object
 2   Vendor            1000 non-null   object
 3   Order Date        1000 non-null   object
 4   Shipping Date     1000 non-null   object
 5   Delivery Date     1000 non-null   object
 6   Region            1000 non-null   object
 7   Delivery Status   1000 non-null   object
 8   Return Status     1000 non-null   object
 9   Return Reason     209 non-null    object
dtypes: object(10)
memory usage: 78.3+ KB

In [7]:
df.describe()

,Order ID,Product Category,Vendor,Order Date,Shipping Date,Delivery Date,Region,Delivery Status,Return Status,Return Reason
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,209
unique,1000,5,3,318,333,339,4,2,2,4
top,ORD0000,Electronics,VendorC,2024-04-22,2024-10-20,2024-12-30,West,Delayed,Not Returned,No reason
freq,1,221,347,9,10,10,262,572,791,59

In [8]:
df.isnull().sum()

Order ID              0
Product Category      0
Vendor                0
Order Date            0
Shipping Date         0
Delivery Date         0
Region                0
Delivery Status       0
Return Status         0
Return Reason       791
dtype: int64

In [9]:
df["Return Reason"].value_counts()

Return Reason
No reason     59
Late          55
Wrong item    55
Damaged       40
Name: count, dtype: int64

# The Return Reason have 791 null values because it is provided only if it has been returned so there are many null values in it. So we just fill the null values with Not Returned.

In [10]:
df["Return Reason"].fillna("Not Returned",inplace=True)

In [11]:
df.isnull().sum()

Order ID            0
Product Category    0
Vendor              0
Order Date          0
Shipping Date       0
Delivery Date       0
Region              0
Delivery Status     0
Return Status       0
Return Reason       0
dtype: int64

In [12]:
df["Return Reason"].value_counts()

Return Reason
Not Returned    791
No reason        59
Late             55
Wrong item       55
Damaged          40
Name: count, dtype: int64

In [13]:
for i in df.columns:
    if df[i].nunique()<20:
        print(df[i].value_counts())

Product Category
Electronics    221
Clothing       203
Books          200
Beauty         188
Home           188
Name: count, dtype: int64
Vendor
VendorC    347
VendorA    335
VendorB    318
Name: count, dtype: int64
Region
West     262
South    253
East     250
North    235
Name: count, dtype: int64
Delivery Status
Delayed      572
Delivered    428
Name: count, dtype: int64
Return Status
Not Returned    791
Returned        209
Name: count, dtype: int64
Return Reason
Not Returned    791
No reason        59
Late             55
Wrong item       55
Damaged          40
Name: count, dtype: int64

# Storing the Data of Returned in a seperate dataframe for easy summarization

In [14]:
df1=df[df["Return Status"]=="Returned"]

In [15]:
df1["Return Reason"].value_counts()

Return Reason
No reason     59
Late          55
Wrong item    55
Damaged       40
Name: count, dtype: int64

In [16]:
for i in df1.columns:
    if df1[i].nunique()<20:
        print(df1[i].value_counts())

Product Category
Electronics    52
Books          42
Beauty         41
Clothing       40
Home           34
Name: count, dtype: int64
Vendor
VendorB    72
VendorA    69
VendorC    68
Name: count, dtype: int64
Region
West     63
East     53
South    51
North    42
Name: count, dtype: int64
Delivery Status
Delayed      124
Delivered     85
Name: count, dtype: int64
Return Status
Returned    209
Name: count, dtype: int64
Return Reason
No reason     59
Late          55
Wrong item    55
Damaged       40
Name: count, dtype: int64

In [17]:
Days=(pd.to_datetime(df["Delivery Date"])-pd.to_datetime(df["Order Date"])).dt.days
df["Delivery Days"]=Days

In [18]:
df1["Order Date"]=pd.to_datetime(df1["Order Date"])

df1["Delivery Date"]=pd.to_datetime(df1["Delivery Date"])

C:\Users\vighnesh\AppData\Local\Temp\ipykernel_5836\2297403697.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Order Date"]=pd.to_datetime(df1["Order Date"])
C:\Users\vighnesh\AppData\Local\Temp\ipykernel_5836\2297403697.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Delivery Date"]=pd.to_datetime(df1["Delivery Date"])

In [19]:
df1.dtypes

Order ID                    object
Product Category            object
Vendor                      object
Order Date          datetime64[ns]
Shipping Date               object
Delivery Date       datetime64[ns]
Region                      object
Delivery Status             object
Return Status               object
Return Reason               object
dtype: object

In [20]:
(df1["Delivery Date"]-df1["Order Date"]).value_counts()

11 days    28
5 days     27
8 days     26
10 days    22
9 days     22
12 days    20
4 days     18
6 days     15
7 days     13
3 days     10
13 days     8
Name: count, dtype: int64

In [21]:
(df1["Delivery Date"]-df1["Order Date"]).dt.days

1       6
6      10
11     10
13      4
16      5
       ..
982     3
987    11
988     3
997    11
999     5
Length: 209, dtype: int64

In [22]:
df1["Delivery Status"].value_counts()

Delivery Status
Delayed      124
Delivered     85
Name: count, dtype: int64

In [23]:
df["Delivery Status"].value_counts()

Delivery Status
Delayed      572
Delivered    428
Name: count, dtype: int64

In [24]:
data=df[::]
data.head(10)

,Order ID,Product Category,Vendor,Order Date,Shipping Date,Delivery Date,Region,Delivery Status,Return Status,Return Reason,Delivery Days
0,ORD0000,Clothing,VendorC,2024-07-20,2024-07-21,2024-07-30,East,Delayed,Not Returned,Not Returned,10
1,ORD0001,Beauty,VendorB,2024-11-11,2024-11-12,2024-11-17,West,Delivered,Returned,Late,6
2,ORD0002,Clothing,VendorB,2024-12-06,2024-12-08,2024-12-14,North,Delayed,Not Returned,Not Returned,8
3,ORD0003,Home,VendorA,2024-12-25,2024-12-26,2024-12-30,East,Delivered,Not Returned,Not Returned,5
4,ORD0004,Clothing,VendorA,2024-05-19,2024-05-22,2024-05-28,West,Delayed,Not Returned,Not Returned,9
5,ORD0005,Home,VendorC,2024-02-26,2024-02-27,2024-03-04,West,Delayed,Not Returned,Not Returned,7
6,ORD0006,Electronics,VendorB,2024-07-12,2024-07-13,2024-07-22,West,Delayed,Returned,Wrong item,10
7,ORD0007,Home,VendorB,2024-04-02,2024-04-04,2024-04-11,North,Delayed,Not Returned,Not Returned,9
8,ORD0008,Home,VendorA,2024-02-26,2024-02-28,2024-03-04,South,Delivered,Not Returned,Not Returned,7
9,ORD0009,Clothing,VendorA,2024-08-21,2024-08-22,2024-08-25,West,Delivered,Not Returned,Not Returned,4

In [25]:
from sklearn.preprocessing import LabelEncoder
data['Product Category'] = LabelEncoder().fit_transform(df['Product Category'])

In [26]:
data['Vendor'] = LabelEncoder().fit_transform(df['Vendor'])

In [27]:
data['Region'] = LabelEncoder().fit_transform(df['Region'])

In [28]:
data['Delivery Status'] = LabelEncoder().fit_transform(df['Delivery Status'])

In [29]:
data['Return Status'] = LabelEncoder().fit_transform(df['Return Status'])

In [30]:
data['Return Reason'] = LabelEncoder().fit_transform(df['Return Reason'])

In [31]:
data["Order Date"]=pd.to_datetime(data["Order Date"])

data['Weekend_Order'] = (data['Order Date'].dt.weekday >= 5).astype(int)

In [32]:
data['Is_Delayed'] = (data['Delivery Days'] > 7).astype(int)

In [33]:
data['Long_Delivery'] = (data['Delivery Days'] > 10).astype(int)

In [34]:
data['Is_Express'] = (data['Delivery Days'] <5).astype(int)

In [35]:
data.head()

,Order ID,Product Category,Vendor,Order Date,Shipping Date,Delivery Date,Region,Delivery Status,Return Status,Return Reason,Delivery Days,Weekend_Order,Is_Delayed,Long_Delivery,Is_Express
0,ORD0000,2,2,2024-07-20,2024-07-21,2024-07-30,0,0,0,3,10,1,1,0,0
1,ORD0001,0,1,2024-11-11,2024-11-12,2024-11-17,3,1,1,1,6,0,0,0,0
2,ORD0002,2,1,2024-12-06,2024-12-08,2024-12-14,1,0,0,3,8,0,1,0,0
3,ORD0003,4,0,2024-12-25,2024-12-26,2024-12-30,0,1,0,3,5,0,0,0,0
4,ORD0004,2,0,2024-05-19,2024-05-22,2024-05-28,3,0,0,3,9,1,1,0,0

In [36]:
df.head()

,Order ID,Product Category,Vendor,Order Date,Shipping Date,Delivery Date,Region,Delivery Status,Return Status,Return Reason,Delivery Days
0,ORD0000,Clothing,VendorC,2024-07-20,2024-07-21,2024-07-30,East,Delayed,Not Returned,Not Returned,10
1,ORD0001,Beauty,VendorB,2024-11-11,2024-11-12,2024-11-17,West,Delivered,Returned,Late,6
2,ORD0002,Clothing,VendorB,2024-12-06,2024-12-08,2024-12-14,North,Delayed,Not Returned,Not Returned,8
3,ORD0003,Home,VendorA,2024-12-25,2024-12-26,2024-12-30,East,Delivered,Not Returned,Not Returned,5
4,ORD0004,Clothing,VendorA,2024-05-19,2024-05-22,2024-05-28,West,Delayed,Not Returned,Not Returned,9

In [37]:
category_return_rate = data.groupby('Product Category')['Return Status'].mean().sort_values(ascending=False)
print(category_return_rate)

Product Category
3    0.235294
0    0.218085
1    0.210000
2    0.197044
4    0.180851
Name: Return Status, dtype: float64

# 0 means Beauty    : 21.8%  Return Rate
# 1 means Books  : 21.0%  Return Rate
# 2 means Clothing   :19.7%  Return Rate
# 3 means Electronics   : 23.5%  Return Rate
# 4 means Home   : 23.5%  Return Rate

In [38]:
vendor_return_rate = data.groupby('Vendor')['Return Status'].mean().sort_values(ascending=False)
print(vendor_return_rate)

Vendor
1    0.226415
0    0.205970
2    0.195965
Name: Return Status, dtype: float64

# 0 : Vendor A : 20.5% Return Rate
# 1 : Vendor B : 20.5% Return Rate
# 2 : Vendor C : 19.5% Return Rate

In [39]:
region_return_rate = data.groupby('Region')['Return Status'].mean()
print(region_return_rate)

Region
0    0.212000
1    0.178723
2    0.201581
3    0.240458
Name: Return Status, dtype: float64

# 0 means East    : 21.8%  Return Rate
# 1 means North  : 21.0%  Return Rate
# 2 means South  :19.7%  Return Rate
# 3 means West   : 23.5%  Return Rate

# Modelling

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score

In [41]:
X = data.drop(['Return Status',"Order ID",'Order Date', 'Shipping Date','Delivery Date'], axis=1)
y = data['Return Status']

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

model = LogisticRegression(class_weight='balanced', max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [43]:
y_probs = model.predict_proba(X_test)[:, 1] 
print("Predicted Probabilities:", y_probs)

Predicted Probabilities: [0.88126854 0.39235265 0.36747282 0.34348399 0.28056915 0.26935266
 0.3370911  0.70221805 0.46646543 0.59707326 0.24775304 0.29652816
 0.42996944 0.45208433 0.44653263 0.3329431  0.08860074 0.37353762
 0.38237026 0.69547077 0.48618595 0.38494613 0.28904407 0.44546595
 0.20099007 0.31991537 0.25002888 0.33198814 0.52450361 0.1140445
 0.47712602 0.3940401  0.91449736 0.91891262 0.27278751 0.52206449
 0.31842585 0.55266538 0.7445293  0.20375301 0.45308491 0.29090367
 0.15656706 0.12022991 0.48199614 0.28550994 0.33681505 0.532727
 0.53886276 0.33628089 0.35842054 0.39923341 0.24312726 0.3780349
 0.32104242 0.34173673 0.43156097 0.50534243 0.36440489 0.61537016
 0.44777777 0.19843617 0.48016395 0.40230735 0.42109855 0.72396925
 0.32821934 0.66731501 0.21192389 0.33279319 0.21773087 0.57429639
 0.34064999 0.32759903 0.23526647 0.83194027 0.34016109 0.45325471
 0.33028629 0.44048456 0.384583   0.41968153 0.28563846 0.23030298
 0.41070651 0.4278761  0.3833695  0.33506231 0.97250354 0.35142435
 0.41575675 0.31839461 0.11382952 0.31224659 0.27387289 0.45955543
 0.37573034 0.91426573 0.47268571 0.39803667 0.39759081 0.32577789
 0.33715072 0.07305401 0.41500844 0.25744209 0.40482673 0.40326385
 0.17116302 0.48760031 0.94330507 0.79096342 0.43928488 0.07411874
 0.96695122 0.45794384 0.34831353 0.13800108 0.26879908 0.23770205
 0.30372911 0.32492302 0.27387289 0.43628852 0.2821578  0.38135125
 0.32481643 0.36973035 0.31858925 0.44880052 0.44594049 0.3361403
 0.34443828 0.26544814 0.25424203 0.38039949 0.29757057 0.81740921
 0.42840922 0.96643979 0.27771698 0.38135125 0.39067462 0.35794229
 0.42078637 0.47212008 0.40729954 0.40245299 0.33198814 0.49992095
 0.31382486 0.26935266 0.05667606 0.82107661 0.27900593 0.39718544
 0.4960792  0.32185195 0.33628089 0.41292819 0.34251114 0.94485138
 0.47506093 0.48747889 0.20460232 0.41344451 0.42392115 0.4980199
 0.39644099 0.51917734 0.33963446 0.39834357 0.33963446 0.26378512
 0.14271856 0.46113505 0.8954327  0.3553356  0.22852728 0.9586469
 0.15656706 0.53287776 0.22952737 0.23511137 0.4593495  0.54508711
 0.39475683 0.412109   0.3255993  0.42983912 0.41575675 0.3361403
 0.35206615 0.24429924 0.95465888 0.50154358 0.1234358  0.22510528
 0.47611567 0.47323101]

In [46]:
print("ROC AUC Score:", roc_auc_score(y_test, y_probs))

ROC AUC Score: 0.7935421762347511

# 79% approximately 80 is okay for now (Need Further Improvements)

In [49]:
print(classification_report(y_test, model.predict(X_test)))

              precision    recall  f1-score   support

           0       0.91      0.92      0.92       162
           1       0.67      0.63      0.65        38

    accuracy                           0.87       200
   macro avg       0.79      0.77      0.78       200
weighted avg       0.86      0.87      0.86       200

In [44]:
data.head(10)

,Order ID,Product Category,Vendor,Order Date,Shipping Date,Delivery Date,Region,Delivery Status,Return Status,Return Reason,Delivery Days,Weekend_Order,Is_Delayed,Long_Delivery,Is_Express
0,ORD0000,2,2,2024-07-20,2024-07-21,2024-07-30,0,0,0,3,10,1,1,0,0
1,ORD0001,0,1,2024-11-11,2024-11-12,2024-11-17,3,1,1,1,6,0,0,0,0
2,ORD0002,2,1,2024-12-06,2024-12-08,2024-12-14,1,0,0,3,8,0,1,0,0
3,ORD0003,4,0,2024-12-25,2024-12-26,2024-12-30,0,1,0,3,5,0,0,0,0
4,ORD0004,2,0,2024-05-19,2024-05-22,2024-05-28,3,0,0,3,9,1,1,0,0
5,ORD0005,4,2,2024-02-26,2024-02-27,2024-03-04,3,0,0,3,7,0,0,0,0
6,ORD0006,3,1,2024-07-12,2024-07-13,2024-07-22,3,0,1,4,10,0,1,0,0
7,ORD0007,4,1,2024-04-02,2024-04-04,2024-04-11,1,0,0,3,9,0,1,0,0
8,ORD0008,4,0,2024-02-26,2024-02-28,2024-03-04,2,1,0,3,7,0,0,0,0
9,ORD0009,2,0,2024-08-21,2024-08-22,2024-08-25,3,1,0,3,4,0,0,0,1

In [45]:
data['Return_Probability'] = model.predict_proba(X)[:, 1]
df['Return_Probability'] = model.predict_proba(X)[:, 1]

In [46]:
data[data['Return_Probability']>=0.7]

,Order ID,Product Category,Vendor,Order Date,Shipping Date,Delivery Date,Region,Delivery Status,Return Status,Return Reason,Delivery Days,Weekend_Order,Is_Delayed,Long_Delivery,Is_Express,Return_Probability
1,ORD0001,0,1,2024-11-11,2024-11-12,2024-11-17,3,1,1,1,6,0,0,0,0,0.891855
11,ORD0011,1,0,2024-07-09,2024-07-10,2024-07-19,3,0,1,1,10,0,1,0,0,0.918078
13,ORD0013,0,2,2024-07-09,2024-07-11,2024-07-13,3,1,1,1,4,0,0,0,1,0.915729
16,ORD0016,3,0,2024-10-10,2024-10-11,2024-10-15,3,1,1,1,5,0,0,0,0,0.845879
27,ORD0027,0,2,2024-06-11,2024-06-14,2024-06-16,3,1,1,1,5,0,0,0,0,0.890675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,ORD0932,3,2,2024-07-04,2024-07-07,2024-07-16,3,0,1,1,12,0,1,1,0,0.891359
945,ORD0945,0,0,2024-08-05,2024-08-08,2024-08-16,3,0,1,0,11,0,1,1,0,0.981707
956,ORD0956,1,1,2024-04-24,2024-04-25,2024-05-03,1,0,1,0,9,0,1,0,0,0.962199
982,ORD0982,2,0,2024-12-07,2024-12-08,2024-12-10,0,1,1,1,3,1,0,0,1,0.846551
997,ORD0997,1,1,2024-05-22,2024-05-23,2024-06-02,2,0,1,0,11,0,1,1,0,0.972496

In [47]:
df.head()

,Order ID,Product Category,Vendor,Order Date,Shipping Date,Delivery Date,Region,Delivery Status,Return Status,Return Reason,Delivery Days,Return_Probability
0,ORD0000,Clothing,VendorC,2024-07-20,2024-07-21,2024-07-30,East,Delayed,Not Returned,Not Returned,10,0.310753
1,ORD0001,Beauty,VendorB,2024-11-11,2024-11-12,2024-11-17,West,Delivered,Returned,Late,6,0.891855
2,ORD0002,Clothing,VendorB,2024-12-06,2024-12-08,2024-12-14,North,Delayed,Not Returned,Not Returned,8,0.365848
3,ORD0003,Home,VendorA,2024-12-25,2024-12-26,2024-12-30,East,Delivered,Not Returned,Not Returned,5,0.184143
4,ORD0004,Clothing,VendorA,2024-05-19,2024-05-22,2024-05-28,West,Delayed,Not Returned,Not Returned,9,0.484504

In [78]:
high_risk = df[df['Return_Probability'] > 0.7]
#high_risk[['Order ID', 'Product Category', 'Return_Probability']].to_csv('high_risk_products.csv', index=False)

In [48]:
df.to_csv('Ecommerce_returns_data.csv',index=False)